### PR TITLE
examples: remove clone.rs example

### PR DESCRIPTION
**Pull request by cvybhu**
`clone.rs` is an old example that uses `SessionBuilder` to build many copies of `Session`.

I think this example is harmful because it promotes the use of multiple Sessions, which is usually a bad idea.

One user started using multiple `Sessions` instead of `Arc<Session>` because they saw such approach in this example: https://github.com/scylladb/scylla-rust-driver/issues/724#issuecomment-1557645457

The example itself isn't very useful. It just uses a Builder to Build sessions, this isn't anything tricky, it's what's expected of the Builder pattern.

I think it would be better to remove it to avoid misleading the users.

Fixes: #727

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] I added relevant tests for new features and bug fixes.
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have provided docstrings for the public items that I want to introduce.
- [x] I have adjusted the documentation in `./docs/source/`.
- [x] I added appropriate `Fixes:` annotations to PR description.

### CODE REVIEW

**Review by wprzytula — COMMENTED** [review]
Although I agree that the particular example is misleading, I believe the aspect of using `Session` from many threads deserves better explanation in docs. We should:
- state that although building multiple `Session`s using a single `SessionBuilder` is possible, shared access to single `Session` through an `Arc` is prefered, 
- compare both options in terms of inner working (disadvantages of multiple `Session`s: duplicated connection pools, precomputed replicas etc., but (as advantages) possibly distinct configuration and clean separation of two workloads (?)).

Before this is described in docs, I oppose the mere removal of this example.

**Comment by wprzytula** [comment]
Taken a look at #216, I think we should alter the `clone.rs` example to put `Session` inside an `Arc` and then use it concurrently from multiple threads. This would give us both:
- no confusion induced by creating multiple `Session`s,
- show the suggested way of sharing `Session`.
WDYT @cvybhu @piodul?

**Review by wprzytula — CHANGES_REQUESTED** [review]
See #216.

**Comment by avelanarius** [comment]
After a second thought, maybe another example is not really neccessary as https://github.com/scylladb/scylla-rust-driver/blob/main/examples/parallel.rs this already shows using `Session` in an `Arc`.

**Comment by piodul** [comment]
I am in favor of removing the example. As @avelanarius wrote, we have the "parallel" example already. We don't need to change "clone" to look like "parallel".

We already mention that the session is able to handle multiple requests in parallel in the documentation, at the end of this page: https://rust-driver.docs.scylladb.com/stable/queries/queries.html

Perhaps we could also add it to the docstring for `Session` so that it appears in the API docs (on docs.rs) - currently the docstring is very laconic. That can be left for a followup.

**Review by piodul — APPROVED** [review]

**Comment by piodul** [comment]
@wprzytula please approve and merge if you agree to remove the example.

**Pull request merged**
