### PR TITLE
docs: update theme 1.5

### PR DESCRIPTION
**Pull request by dgarcia360**
Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/774

ScyllaDB Sphinx Theme 1.5 is now released 🥳 This update introduces an interactive feature to receive feedback, allowing readers to like or dislike documentation pages. It also includes subtle user interface enhancements and resolves an existing issue related to the sitemap extension. 

You can read more about all notable changes [here](https://sphinx-theme.scylladb.com/master/upgrade/CHANGELOG.html#may-2023).

## How to test this PR

1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).

2. Enter the docs folder, and run:
  
    ```
    make preview
    ````

3. Open http://localhost:5500 with your favorite browser. The doc should render without errors, and the version should be Sphinx Theme version (see the footer) must be ``1.5.x``:

    image

### CODE REVIEW

**Comment by wprzytula** [comment]
Having run `make preview`, I've faced:
```
poetry install
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Because sphinx-docs depends on sphinx-sitemap (2.5.0) which doesn't match any versions, version solving failed.
make: *** [Makefile:31: setup] Error 1
```
Running `poetry lock`, as suggested, solved the issue though.

**Comment by wprzytula** [comment]
I get warnings about naming:
```
WARNING: Document name contains underscores: queries/schema_agreement
WARNING: Document name contains underscores: retry-policy/downgrading_consistency
```

as well as warnings related to consistency:
```
checking consistency... /home/wojciech/scylla-rust-driver/docs/_source/load-balancing/dc-robin.md: WARNING: document isn't included in any toctree
/home/wojciech/scylla-rust-driver/docs/_source/load-balancing/robin.md: WARNING: document isn't included in any toctree
/home/wojciech/scylla-rust-driver/docs/_source/load-balancing/token-dc-robin.md: WARNING: document isn't included in any toctree
/home/wojciech/scylla-rust-driver/docs/_source/load-balancing/token-robin.md: WARNING: document isn't included in any toctree
/home/wojciech/scylla-rust-driver/docs/_source/queries/schema_agreement.md: WARNING: document isn't included in any toctree
/home/wojciech/scylla-rust-driver/docs/_source/retry-policy/downgrading_consistency.md: WARNING: document isn't included in any toctree
```
@piodul

**Comment by dgarcia360** [comment]
@wprzytula I've pushed a new commit. Could you please download the latest version and run ``make clean`` before `make preview`?

```
cd docs
make clean
make preview
```

**Comment by wprzytula** [comment]
> @wprzytula I've pushed a new commit. Could you please download the latest version and run `make clean` before `make preview`?
> 
> ```
> cd docs
> make clean
> make preview
> ```

Thanks @dgarcia360, now everything runs smoothly.

**Review by piodul — APPROVED** [review]

**Pull request merged**
