### PR TITLE
Query Builder 2.0

### PR DESCRIPTION
**Pull request by cvybhu**
## Description
Old PR for `QueryBuilder` (#71) is dead, this is the new one.

It adds a `QueryBuilder` that makes creating `Query` convenient.
It can be used like this:
```rust
let query: Query = QueryBuilder::new("SELECT * FROM keyspace.table")
    .page_size(128)
    .consistency(Consistency::LocalQuorum)
    .build();
```

### Other possible features
I was thinking about other features, but I'm not sure if they are really needed.
We could allow running a query from `QueryBuilder` like this:
```rust
QueryBuilder::new("SELECT * FROM keyspace.table")
   .page_size(128)
   .consistency(Consistency::LocalQuorum)
   .run(&session, (1, "abc"))
   .await?;
```
And maybe preparing them too?
```rust
QueryBuilder::new("SELECT * FROM keyspace.table")
   .page_size(128)
   .consistency(Consistency::LocalQuorum)
   .prepare(&session, (1, "abc"))
   .await?;
````
Pros:
* Shorter code

Cons:
* Cyclic dependency `Query` <-> `Session`
* Two ways to do the same thing
* More complicated code

### Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] I added relevant tests for new features and bug fixes.
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I added appropriate `Fixes:` annotations to PR description.

### CODE REVIEW

**Comment by psarna** [comment]
That's a good start,  we should also consider making the builder powerful enough that statements strings aren't needed (not in this PR, but for the future ones). E.g.
```rust
let ks_query = QueryBuilder::new_keyspace("test_keyspace").replication_strategy(SimpleStrategy(3));
```

**Comment by Ponewor** [comment]
What's the status of this one? I'm heavily interested in implementing what @psarna has described and getting rid of query strings, but I'm still waiting for this PR.

**Comment by psarna** [comment]
> What's the status of this one? 

Long forgotten. Feel free to work on your own series on top of @cvybhu's commit, we can then merge it all in a single PR. This particular PR wasn't merged because nobody was sure if the interface is right - and I guess that we'll only know that if we implement more features and see if the base interface fits to our needs.

**Comment by cvybhu** [comment]
This PR is now 1.5 years old and has been forgotten. Let's close it, it can be reopened later if we decide to work in this direction.

**Pull request closed without merging**
