### PR TITLE
Add serial_consistency support for queries, prepared statements, and batch statements. (LWT Basis)

### PR DESCRIPTION
**Pull request by dtzxporter**
Adds support for setting serial_consistency for queries, prepared statements, and batch statements. This provides the basis for LWT support (#100)

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [ ] I added relevant tests for new features and bug fixes.
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I added appropriate `Fixes:` annotations to PR description.

### CODE REVIEW

**Comment by psarna** [comment]
Looks good - how was this change tested? Could you add either a test case which runs against Scylla (like this one: https://github.com/scylladb/scylla-rust-driver/blob/cfd6fa55e18995cc23a427e6fe076e83c8ab847d/scylla/src/transport/session_test.rs#L181-L244 , it's marked as ignored in order to not run during CI and requires a local Scylla node), or add an example program in /examples which shows how the new feature can be used?

Also, before the pull request gets merged, please squash the 01375cbc953438b69e16f86adff204baed6bb92e commit with its parent (7bdcb8b2f185238fd87da0f17e45fbbccae238f3), so that the series does not contain fixes to itself - which we try to avoid in order to keep each series bisectable, in case we need to look for errors later.

**Comment by dtzxporter** [comment]
Hi! I'll get through this when I have time. The other thing is, the node driver sends one by default (because the Db ignores it when query isn't LWT) and its only two extra bytes (and one flag) which we may want to do? Thoughts on this?

**Comment by psarna** [comment]
Sure, no rush. As for always sending the serial consistency - I think that it's better to only send these additional bytes if they're going to be used. The overhead per single request is minor, but 100 clients sending 10k requests per second would force Scylla to read 2MB of junk per second - so since it's easy to avoid the overhead by setting a flag on the client side only if necessary, it's better to do so.

**Comment by psarna** [comment]
I'm merging as is, a follow-up issue is created here: #197

**Pull request merged**
