### PR TITLE
default_lb: Enrich comments & docstrings

### PR DESCRIPTION
**Pull request by wprzytula**
The DefaultPolicy is a complex machinery. In order to grasp it fully, extensive comments are essential.
Some internal functions' names were changed, to make them more better reflect the functions' semantics.

## Pre-review checklist

- [ ] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- ~~[ ] I added relevant tests for new features and bug fixes.~~
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~~[ ] I have provided docstrings for the public items that I want to introduce.~~
- ~~[ ] I have adjusted the documentation in `./docs/source/`.~~
- ~~[ ] I added appropriate `Fixes:` annotations to PR description.~~

### CODE REVIEW

**Review by Lorak-mmk — CHANGES_REQUESTED** [review]
Great PR!
I'd add a description for `DefaultPolicyTargetComparator` because it is definitely not obvious what that is or why it is present.
I propose the following, lmk what you think:
```
Plan should return unique elements. It is not however obvious what it means because some nodes in the plan may have shards and some may not.
This helper structure defines equality of plan elements.
How the comparison works:
- If at least one of elements is shard-less then compare just nodes.
- If both elements have shards, then compare both nodes and shards.
Why is it implemented this way?
Driver should not attempt to send the same request to the same destination twice.
If plan element doesn't have shard specified, then a random shard will be chosen by the driver.
If the plan also contains the same node but with the shard present, and we randomly chose the same shard for the shard-less element, then we have duplication.
Example: plan is `[(Node1, Some(1)), (Node1, None)]` - if the driver uses the second element and randomly chooses shard 1, then we have a duplication.

On the other hand if the plan has a duplicate node, but with different shards, then we want to use both elements - so we can't just make the list unique by node, and so this struct was created.
```

**Comment by wprzytula** [comment]
v1.1: justified why latency awareness is not recommended.

**Comment by wprzytula** [comment]
> I propose the following, lmk what you think:

Wonderful, I'll include it in the PR.

**Comment by wprzytula** [comment]
v1.2: added  `DefaultPolicyTargetComparator` docstring.

**Review by Lorak-mmk — APPROVED** [review]

**Comment by wprzytula** [comment]
v1.2.1: clippy fixes.

**Pull request merged**
