### PR TITLE
CQL Tracing

### PR DESCRIPTION
**Pull request by cvybhu**
## Description
This PR adds support for CQL tracing.
Tracing can be used like this:
```rust
// Create a simple query and enable tracing for it
let mut query: Query = Query::new("SELECT peer from system.peers".to_string());
query.set_tracing(true);

// QueryResult will contain a tracing_id which can be used to query tracing information
let query_result: QueryResult = session.query(query.clone(), &[]).await?;
let query_tracing_id: Uuid = query_result
    .tracing_id
    .ok_or_else(|| anyhow!("Tracing id is None!"))?;

// Get tracing information for this query and print it
let tracing_info: TracingInfo = session.get_tracing_info(&query_tracing_id).await?;
println!("Query tracing info: {:#?}\n", tracing_info);
```
Queries that support tracing are:
* `Session::query()`
* `Session::prepare()`
* `Session::execute()`
* `Session::batch()`
* `Session::query_iter()`
* `Session::execute_iter()`

~~In the [specification](https://github.com/apache/cassandra/blob/28e8632c9793f8d77247fc40f2c5003810df16f9/doc/native_protocol_v4.spec#L116) it's written that only QUERY, PREPARE and EXECUTE queries support tracing so `Session::batch()` doesn't support it.~~

## Notes
`TracingInfo` contains columns from `system_traces` that are the same in Cassandra and Scylla. Scylla has some scylla specific entries that the user can query themselves if they really need to.

Retrying tracing info queries and its configuration is based on [DataStax Java Driver](https://docs.datastax.com/en/developer/java-driver/4.0/manual/core/tracing/)

## Fixed issues
Fixes: #189

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] I added relevant tests for new features and bug fixes.
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I added appropriate `Fixes:` annotations to PR description.

### CODE REVIEW

**Comment by cvybhu** [comment]
The tests pass on my machine but fail in CI for some reason 0_o. Gonna investigate.

**Comment by psarna** [comment]
Probably related to timing - tracing data ends up in the tracing tables asynchronously, so you might need to try fetching the appropriate tracing id in a loop.

By the way, contrary to the protocol spec Scylla does support tracing batches, it's an important debugging mechanism, so we'd want to eventually support it in the driver too.

**Comment by cvybhu** [comment]
> Probably related to timing - tracing data ends up in the tracing tables asynchronously, so you might need to try fetching the appropriate tracing id in a loop.

:+1: Added retrying in tests, also Cassandra sometimes had a `null` in the table which the code handled incorrectly, all fixed now.

> By the way, contrary to the protocol spec Scylla does support tracing batches, it's an important debugging mechanism, so we'd want to eventually support it in the driver too.

Added

**Comment by cvybhu** [comment]
@piodul @psarna Rebased and ready for review

**Review by psarna — APPROVED** [review]

**Comment by psarna** [comment]
@cvybhu Looks good, but please also rebase on top of /main - after merging TLS, a small manual translation of this layer to `QueryResult` is in order.

**Comment by cvybhu** [comment]
@psarna rebased and ready

**Pull request merged**
