### PR TITLE
CQL types 

### LINKED ISSUE #104: Support CQL collection types: lists, sets, maps, tuples, frozen<> and not frozen
Part of #97

### PR DESCRIPTION
**Pull request by asledz**
## Description

PR adds CQL types. 
Add time and dates, floating point numbers, booleans and blobs, serializers and deserializers.

Add test (and example of usage at the same time).
I moved the commits to the new branch and created new PR, the old one is here: PR #148 (decided to move because of the issues with merge).

Refs #104 

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] I added relevant tests for new features and bug fixes.
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I added appropriate `Fixes:` annotations to PR description.

### CODE REVIEW

**Comment by asledz** [comment]
@piodul ready for final review, test is passing.

Although format check is not passing (on files that I didn't change)  - and locally it does (not only on my computer) - not sure what to do with this yet, I'll try to figure it out.

**Comment by asledz** [comment]
> @piodul ready for final review, test is passing.
> 
> Although format check is not passing (on files that I didn't change) - and locally it does (not only on my computer) - not sure what to do with this yet, I'll try to figure it out.

Fixed, everything is ready.

**Review by psarna — COMMENTED** [review]
It looks like not all types were implemented in this pull request, so it cannot claim to fix #104. It's ok to leave this pull request as is and provide the rest of the types in a follow-up (with high priority), but the message may only claim to "Ref #104", not fix it.

**Review by psarna — COMMENTED** [review]
I'm merging this pull request as is to push the development forward. It still doesn't fix issue #104 entirely, so I'm changing the description to only `Ref` this issue and will create follow-up issues with missing items.

**Pull request merged**
