### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by Lorak-mmk**
This PR is to review the changes required to release new version. It should NOT be merged, so I opened it as a draft.
After the approve, I will perform following steps (correct me if I'm wrong @piodul):
- `git checkout branch-0.11.x`
- `git tag -a v0.11.0`
- `git push origin v0.11.0`
- `git checkout main`
- `git merge --ff-only branch-0.11.x`
- `git push origin main`
- Check that documentation was built and published successfully
- Create a github release with previously approved release notes
- Push new version to crates.io:
- Create post on the forum about release

## Pre-review checklist

- [ ] I have split my patch into logically separate commits.
- [ ] All commit messages clearly explain what they change and why.
- [ ] I added relevant tests for new features and bug fixes.
- [ ] All commits compile, pass static checks and pass test.
- [ ] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have provided docstrings for the public items that I want to introduce.
- [ ] I have adjusted the documentation in `./docs/source/`.
- [ ] I added appropriate `Fixes:` annotations to PR description.

### CODE REVIEW

**Comment by Lorak-mmk** [comment]
CI fails because:
1. I didn't update Cargo.lock.msrv - will fix it in a moment
2. Some issue with Sphinx theme. Opened and issue about it here: https://github.com/scylladb/sphinx-scylladb-theme/issues/966

**Comment by Lorak-mmk** [comment]
Fixed the Cargo.lock issue. Now the only release blocker is the sphinx theme issue :(

**Comment by piodul** [comment]
The commits and the procedure looks good. Before giving approval, I'll wait until the docs issue is fixed and we get a green light on all jobs.

**Review by piodul — APPROVED** [review]
The docs issue was fixed. Approving.

**Pull request merged**
