### PR TITLE
Improve ergonomics of handling response data

### PR DESCRIPTION
**Pull request by cvybhu**
### Description

`QueryResult` now has helper functions for common use cases
when receieving rows:

```rust
impl QueryResult {
    /// Returns the number of received rows.  
    /// Fails when the query isn't of a type that could return rows, same as [`rows()`](QueryResult::rows).
    pub fn rows_num(&self) -> Result<usize, RowsExpectedError>;

    /// Returns the received rows when present.  
    /// If `QueryResult.rows` is `None`, which means that this query is not supposed to return rows (e.g `INSERT`), returns an error.  
    /// Can return an empty `Vec`.
    pub fn rows(self) -> Result<Vec<Row>, RowsExpectedError>;

    /// Returns the received rows parsed as the given type.  
    /// Equal to `rows()?.into_typed()`.  
    /// Fails when the query isn't of a type that could return rows, same as [`rows()`](QueryResult::rows).
    pub fn rows_typed<RowT: FromRow>(self) -> Result<TypedRowIter<RowT>, RowsExpectedError>;

    /// Returns `Ok` for a result of a query that shouldn't contain any rows.  
    /// Will return `Ok` for `INSERT` result, but a `SELECT` result, even an empty one, will cause an error.  
    /// Opposite of [`rows()`](QueryResult::rows).
    pub fn result_not_rows(&self) -> Result<(), RowsNotExpectedError>;

    /// Returns rows when `QueryResult.rows` is `Some`, otherwise an empty Vec.  
    /// Equal to `rows().unwrap_or_default()`.
    pub fn rows_or_empty(self) -> Vec<Row> ;

    /// Returns rows parsed as the given type.  
    /// When `QueryResult.rows` is `None`, returns 0 rows.  
    /// Equal to `rows_or_empty().into_typed::<RowT>()`.
    pub fn rows_typed_or_empty<RowT: FromRow>(self) -> TypedRowIter<RowT>;

    /// Returns first row from the received rows.  
    /// When the first row is not available, returns an error.
    pub fn first_row(self) -> Result<Row, FirstRowError>;

    /// Returns first row from the received rows parsed as the given type.  
    /// When the first row is not available, returns an error.
    pub fn first_row_typed<RowT: FromRow>(self) -> Result<RowT, FirstRowTypedError>;

    /// Returns `Option<RowT>` containing the first of a result.  
    /// Fails when the query isn't of a type that could return rows, same as [`rows()`](QueryResult::rows).
    pub fn maybe_first_row(self) -> Result<Option<Row>, RowsExpectedError>;

    /// Returns `Option<RowT>` containing the first of a result.  
    /// Fails when the query isn't of a type that could return rows, same as [`rows()`](QueryResult::rows).
    pub fn maybe_first_row_typed<RowT: FromRow>(self) -> Result<Option<RowT>, MaybeFirstRowTypedError>;

    /// Returns the only received row.  
    /// Fails if the result is anything else than a single row.  
    pub fn single_row(self) -> Result<Row, SingleRowError>;

    /// Returns the only received row parsed as the given type.  
    /// Fails if the result is anything else than a single row.  
    pub fn single_row_typed<RowT: FromRow>(self) -> Result<RowT, SingleRowTypedError>;
}
```

This reduces the example in the [issue](https://github.com/scylladb/scylla-rust-driver/issues/214) by 4 lines.
Before:
```rust
let (read_timeuuid,): (Uuid,) = session
    .query("SELECT val from ks.timeuuid_tests", &[]) // 1. create a future which will execute the query
    .await                                           // 2. await the future
    .unwrap()                                        // 3. handle possible error (from db, or transport error)
    .rows                                            // 4. QueryResult has multiple fields, "rows" has the data
    .unwrap()                                        // 5. "rows" is an Option<Vec<Row>>, need to unwrap it
    .into_typed::<(Uuid,)>()                         // 6. turn it into TypedRowIter
    .next()                                          // 7. get the first value from the iterator (which is an Option)
    .unwrap()                                        // 8. unwrap the option
    .unwrap();                                       // 9. TypedRowIter parses rows on the fly, so it returns results - handle it
```

After:
```rust
let (read_timeuuid,): (Uuid,) = session
    .query("SELECT val from ks.timeuuid_tests", &[]) // 1. create a future which will execute the query
    .await                                           // 2. await the future
    .unwrap()                                        // 3. handle possible error (from db, or transport error)
    .first_row_typed::<(Uuid,)>()                    // 4. Get first row as the given type
    .unwrap();                                       // 5. Unwrap the result, might fail if there are no rows or parsing fails
```

### Issues
Fixes: #214

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] I added relevant tests for new features and bug fixes.
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I added appropriate `Fixes:` annotations to PR description.

### CODE REVIEW

**Comment by psarna** [comment]
If I read the code correctly, the only backward-incompatible change is the translation from `Option<Vec<Row>>` to `Vec<Row>` + `bool`, right? I think that in this case it's slightly better for `Option<Vec<Row>>` to stay after all... it sounds more natural than consulting an additional boolean. The rest of the helper functions added in this series are very good, but I'm less sure about dropping the `Option`. @piodul I'd appreciate a second opinion.

**Comment by piodul** [comment]
> If I read the code correctly, the only backward-incompatible change is the translation from `Option<Vec<Row>>` to `Vec<Row>` + `bool`, right? I think that in this case it's slightly better for `Option<Vec<Row>>` to stay after all... it sounds more natural than consulting an additional boolean. The rest of the helper functions added in this series are very good, but I'm less sure about dropping the `Option`. @piodul I'd appreciate a second opinion.

I agree. Having an `Option<Rows>` seems better to me because we force the user if the response had rows. It's easy to forget to check the `response_had_rows` flag if the user can directly access `rows`.

**Comment by cvybhu** [comment]
I will change the `rows` field to `Option<Vec<result::Row>>`

I could add a getter like
```rust
pub fn rows(self) -> Vec<result::Row> {
    self.rows.unwrap_or(Vec::new())
}
```

Should all methods of `QueryResult` return an `Option<>`? 
I feel like this would hurt ergonomics, we would have to write `if let Some()` everywhere :/

**Comment by psarna** [comment]
Depends on each option - warnings, for instance, are totally fine being just a vector. And a `rows()` getter which unpacks the optional makes sense too - some queries, like `SELECT`, are known to return rows, so users will be able to use the helper function.

**Comment by cvybhu** [comment]
@psarna I added `Option` back, it should be OK now

**Review by psarna — APPROVED** [review]

**Comment by cvybhu** [comment]
@psarna @piodul Could we merge this?

**Comment by piodul** [comment]
@cvybhu I'll post some comments tomorrow. I wanted to write them today, but I was occupied with other things and I forgot - sorry about that.

**Review by piodul — CHANGES_REQUESTED** [review]
I'd like the methods to be more strict about checking the conditions. In my mind, those shorthands should be designed for people who expect the result to be in a particular shape. If the result does not conform to the shape, an error should be returned.

The methods currently proposed are a little lax - for example, `rows()` returns an empty Vec if the response if not `Rows`. Another example: `first_row_typed` returns the first row but does not fail if there are more rows in response.

----

For example, I want to do an `INSERT` operation. This operation should return a response with no rows - anything different indicates a mistake and should result in an error. In this case, I expect something like this:

```rust
session
    .query("INSERT INTO ks.t (pk, ck, v) VALUES (1, 2, 3)", &[])
    .await?
    .no_result()?;
```

If a response with rows is returned, the `no_result()` method should fail. I'm not sure about LWT, however - I think some data is returned in its case. So, maybe this method is a bad idea.

Another common use case is returning a single row:

```rust
// Will return an error if:
// - Other response than Rows is returned,
// - There is more than one row in the response
let age = session
    .query("SELECT age FROM ks.t2 WHERE username = ?", &["abc"])
    .await?
    .single_row()?
    .ok_or(|| anyhow!("No information about the age of user abc"))?
    .into_typed_row::<(i32,)>()?; // Maybe we should add a IntoRow trait, complementary to FromRow?

```

This method should behave in a similar way as `first_row_typed` but will report an error if more than one rows is returned - because this indicates a bug in the query and is not what the user wants. I guess that the "row is missing" case is a common one, so returning an `Option` still makes sense for me.

The last method would be for returning multiple rows (e.g. user wants all rows in the partition). In this case the `query_iter` interface probably makes more sense, but for fetching small partitions or small tables this might be OK:

```rust
let ages_iter = session
    .query("SELECT username, age from ks.t")
    .await?
    .rows()?
    .into_typed::<(String, i32,)>();
```

WDUT @psarna @cvybhu ?

**Comment by cvybhu** [comment]
How about something like this?
```rust
// Returns ok when the response is NOT rows
pub fn no_rows(&self) -> Result<(), RowsNotExpectedErr>;

// Returns rows when present, fails otherwise
pub fn rows(self) -> Result<Vec<Row>, RowsExpectedErr>;
pub fn rows_typed<RowT: FromRow>(self) -> Result<TypedRowIter<RowT>, RowsExpectedErr>;

// Returns rows when present, otherwise an empty Vec/Iterator
pub fn rows_or_empty(self) -> Vec<Row>;
pub fn rows_typed_or_empty<RowT: FromRow>(self) -> TypedRowIter<RowT>;

// Returns Option<Row> when rows are present, fails when not present
pub fn maybe_first_row(self) -> Result<Option<Row>, RowsExpectedErr>;
pub fn maybe_first_row_typed<RowT: FromRow> -> Result<Option<RowT>, MaybeFirstRowTypedErr>;

// Returns the first row when present, fails otherwise
pub fn first_row(self) -> Result<Row, FirstRowErr>;
pub fn first_row_typed<RowT: FromRow>(self) -> Result<RowT, FirstRowTypedErr>;

// Fails if the result is anything else than a single row
pub fn single_row(self) -> Result<Row, SingleRowError>;
pub fn single_row_typed<RowT: FromRow>(self) -> Result<RowT, SingleRowTypedError>;
```

**Comment by piodul** [comment]
> How about something like this?
> 
> ```rust
> // Returns ok when the response is NOT rows
> pub fn no_rows(&self) -> Result<(), RowsNotExpectedErr>;
> 
> // Returns rows when present, fails otherwise
> pub fn rows(self) -> Result<Vec<Row>, RowsExpectedErr>;
> pub fn rows_typed<RowT: FromRow>(self) -> Result<TypedRowIter<RowT>, RowsExpectedErr>;
> 
> // Returns rows when present, otherwise an empty Vec/Iterator
> pub fn rows_or_empty(self) -> Vec<Row>;
> pub fn rows_typed_or_empty<RowT: FromRow>(self) -> TypedRowIter<RowT>;
> 
> // Returns Option<Row> when rows are present, fails when not present
> pub fn maybe_first_row(self) -> Result<Option<Row>, RowsExpectedErr>;
> pub fn maybe_first_row_typed<RowT: FromRow> -> Result<Option<RowT>, MaybeFirstRowTypedErr>;
> 
> // Returns the first row when present, fails otherwise
> pub fn first_row(self) -> Result<Row, FirstRowErr>;
> pub fn first_row_typed<RowT: FromRow>(self) -> Result<RowT, FirstRowTypedErr>;
> 
> // Fails if the result is anything else than a single row
> pub fn single_row(self) -> Result<Row, SingleRowError>;
> pub fn single_row_typed<RowT: FromRow>(self) -> Result<RowT, SingleRowTypedError>;
> ```

I don't like that there are two versions of each shorthand (except for `no_rows`). I feel the operations "assert that result has some kind of rows" and "impose row type" are orthogonal, and the proposed shorthands are a cartesian product of them. I imagine that each time we add another kind of operation (although I don't have any idea at the moment what this operation would be) we would have to multiply the number of shorthands.

@psarna thoughts? Maybe my worries are unfounded...

**Comment by cvybhu** [comment]
Also `no_rows()` is a bad name, maybe `result_not_rows()`?

**Comment by cvybhu** [comment]
I uploaded a prototype of how the new version would look like, but it still needs more docs and tests

**Comment by Jasperav** [comment]
@cvybhu is there any update on this PR?

**Comment by cvybhu** [comment]
> @cvybhu is there any update on this PR?

I will get back to it soon

**Comment by cvybhu** [comment]
I accidentally force pushed the branch with 0 commits and github closed the PR, but now it's fine.

**Comment by cvybhu** [comment]
v2:
* All `QueryResult` methods now check if the response was `Rows`
* Split changes into multiple commits for easier review
* Added unit tests for `QueryResult` methods

**Comment by cvybhu** [comment]
Closed in favor of #348

**Pull request closed without merging**
