### PR TITLE
codewide: Decrease excessive visibility from `pub` - nonbreaking changes

### PR DESCRIPTION
**Pull request by wprzytula**
In spirit of the referenced issue, `scylla` crate is saved from the hazardous siege of `pub` qualifiers. This PR collects the changes that I believe to be non-breaking, so that they can be merged immediately.

Refs: #660 

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- ~~[ ] I added relevant tests for new features and bug fixes.~~
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~~[ ] I have provided docstrings for the public items that I want to introduce.~~
- ~~[ ] I have adjusted the documentation in `./docs/source/`.~~
- ~~[ ] I added appropriate `Fixes:` annotations to PR description.~~

### CODE REVIEW

**Review by piodul — COMMENTED** [review]
Looks good apart from one comment.

I'm worried that we might introduce more items that superficially look public but are actually not. I hope that, in the future, with a module structure that is more thought out than the current one, it will become more obvious whether `pub` items are actually visible based on their location...

**Comment by wprzytula** [comment]
> Looks good apart from one comment.
> 
> I'm worried that we might introduce more items that superficially look public but are actually not. I hope that, in the future, with a module structure that is more thought out than the current one, it will become more obvious whether `pub` items are actually visible based on their location...

A simple way to prevent _false `pub`s_ is to stop using them without a strong need to do so. I can see this has become the new way in the driver recently, as before it was popular to keep methods or fields `pub` regardless of the level of user's intended access to them.

**Comment by wprzytula** [comment]
v2: dropped the controversial commit regarding `MetadataReader` associated functions.

**Comment by piodul** [comment]
> v2: dropped the controversial commit regarding MetadataReader associated functions.

@wprzytula I think you dropped the wrong commit - the one that unpubs methods of the metadata reader, not the ones that convert some free functions to static methods.

**Comment by wprzytula** [comment]
> > v2: dropped the controversial commit regarding MetadataReader associated functions.
> 
> @wprzytula I think you dropped the wrong commit - the one that unpubs methods of the metadata reader, not the ones that convert some free functions to static methods.

I should be OK now.

**Review by piodul — APPROVED** [review]

**Pull request merged**
