### PR TITLE
types: serialize: constrain the new serialization traits to make them easier and safer to use

### PR DESCRIPTION
**Pull request by piodul**
Currently, `SerializeRow` and `SerializeCql` traits are just given a mutable reference to a Vec<u8> and asked to append their CQL representation to the end. While simple, there are some issues with the interface:

- The serialize method has access to the serialized representation of the values that were appended before it. It's not necessary for a correct implementation to have access to it.
- Implementors technically can append any byte sequence to the end, but actually are expected to produce a CQL [value] containing the serialized value.

While the `SerializeRow` and `SerializeCql` traits are not generally meant to be manually implemented by the users, we can make the interface easier to use and harder to misuse by making it append-only, restricting what the users are allowed to append and requiring the users to append anything by using a dash of type-level magic.

Introduce `RowWriter` and `CellWriter` traits which satisfy the above wishes and constraints, and pass them instead of Vec<u8> in `SerializeRow` and `SerializeCql`.

The new traits have two implementations - a Vec<u8> backed one that actually appends the bytes given to it, and a usize-backed one which just measures the length of the output without writing anything. Passing the latter before doing the actual serialization will allow to preallocate the right amount of bytes and then serialize without reallocations. It should be measured whether the reallocation cost always outweighs the calculation cost before implementing this optimization.

Refs: https://github.com/scylladb/scylla-rust-driver/issues/801

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] I added relevant tests for new features and bug fixes.
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have provided docstrings for the public items that I want to introduce.
- [ ] ~I have adjusted the documentation in `./docs/source/`.~
- [ ] ~I added appropriate `Fixes:` annotations to PR description.~

### CODE REVIEW

**Comment by piodul** [comment]
@Lorak-mmk review ping

**Comment by piodul** [comment]
v2:
- More docstrings
- RowWriter now does not prepend what it wrote with a u16 value indicating the count of the values written
- Some items that were accidentally imported via `_macro_internal` path in tests are now imported through a proper path

**Comment by piodul** [comment]
v2.1:
- Rebased
- Addressed clippy's complaints about needless `std::mem::drop`

**Review by Lorak-mmk — APPROVED** [review]

**Comment by Lorak-mmk** [comment]
Actually I have one question: is mod.rs the best place for those new traits and structs? I don't really know Rust conventions in this matter, but it is quite a lot of code, wouldn't it be better to make a new file for it?

**Comment by piodul** [comment]
> Actually I have one question: is mod.rs the best place for those new traits and structs? I don't really know Rust conventions in this matter, but it is quite a lot of code, wouldn't it be better to make a new file for it?

Makes sense, I can move the `CellWriter` and friends to a separate module.

**Comment by piodul** [comment]
v3.1: fixed links in the docs

**Review by Lorak-mmk — APPROVED** [review]
I think there is nothing blocking this, do you think we can merge it?

**Comment by piodul** [comment]
> I think there is nothing blocking this, do you think we can merge it?

Yes, I'll go ahead and merge it.

**Pull request merged**
