### PR TITLE
docs: update theme 1.7

### PR DESCRIPTION
**Pull request by dgarcia360**
Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/1035

ScyllaDB Sphinx Theme 1.7 is out 🥳 Now, the docs will automatically publish when backporting changes to previous branches. This release also introduces minor style enhancements to the sidebar and homepage.

You can read more about all notable changes [here](https://sphinx-theme.scylladb.com/master/upgrade/CHANGELOG.html#apr-2024).

## How to test this PR

1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).

2. Enter the docs folder, and run:
  
    ```
    make preview
    ````

3. Open http://localhost:5500 with your favorite browser. The doc should render without errors, and the version should be Sphinx Theme version (see the footer) must be ``1.7.x``:

image

### CODE REVIEW

**Comment by dgarcia360** [comment]
cc/ @annastuchlik

**Comment by wprzytula** [comment]
Having installed poetry using dnf:
`sudo dnf install poetry` 
and run `make preview`, I got an error:
```
Writing lock file
poetry update
Updating dependencies
Resolving dependencies... (1.3s)

No dependencies to install or update
cp -TLr source _source
python _utils/prepare_sphinx_source.py _source
Preparing sphinx source in _source
OK Done - prepared sphinx source is in _source
poetry run sphinx-autobuild -b dirhtml -d _build/doctrees  -j auto _source _build/dirhtml --port 5500
[sphinx-autobuild] > sphinx-build -b dirhtml -d _build/doctrees -j auto /home/wojciech/Repos/rust-driver-playground/docs/_source /home/wojciech/Repos/rust-driver-playground/docs/_build/dirhtml
Running Sphinx v7.2.6
/home/wojciech/.cache/pypoetry/virtualenvs/sphinx-docs-B6yYV2vv-py3.12/lib/python3.12/site-packages/sphinx_scylladb_theme/lexers/cql.py:236: SyntaxWarning: invalid escape sequence '\s'
  r"(" + "|".join(s.replace(" ", "\s+") for s in DATATYPES) + r")\b",

Extension error:
Could not import extension sphinx_multiversion (exception: No module named 'distutils')
Command exited with exit code: 2
The server will continue serving the build folder, but the contents being served are no longer in sync with the documentation sources. Please fix the cause of the error above or press Ctrl+C to stop the server.
[I 240514 07:51:51 server:335] Serving on http://127.0.0.1:5500
```

**Comment by Lorak-mmk** [comment]
> Having installed poetry using dnf: `sudo dnf install poetry` and run `make preview`, I got an error:
> 
> ```
> Writing lock file
> poetry update
> Updating dependencies
> Resolving dependencies... (1.3s)
> 
> No dependencies to install or update
> cp -TLr source _source
> python _utils/prepare_sphinx_source.py _source
> Preparing sphinx source in _source
> OK Done - prepared sphinx source is in _source
> poetry run sphinx-autobuild -b dirhtml -d _build/doctrees  -j auto _source _build/dirhtml --port 5500
> [sphinx-autobuild] > sphinx-build -b dirhtml -d _build/doctrees -j auto /home/wojciech/Repos/rust-driver-playground/docs/_source /home/wojciech/Repos/rust-driver-playground/docs/_build/dirhtml
> Running Sphinx v7.2.6
> /home/wojciech/.cache/pypoetry/virtualenvs/sphinx-docs-B6yYV2vv-py3.12/lib/python3.12/site-packages/sphinx_scylladb_theme/lexers/cql.py:236: SyntaxWarning: invalid escape sequence '\s'
>   r"(" + "|".join(s.replace(" ", "\s+") for s in DATATYPES) + r")\b",
> 
> Extension error:
> Could not import extension sphinx_multiversion (exception: No module named 'distutils')
> Command exited with exit code: 2
> The server will continue serving the build folder, but the contents being served are no longer in sync with the documentation sources. Please fix the cause of the error above or press Ctrl+C to stop the server.
> [I 240514 07:51:51 server:335] Serving on http://127.0.0.1:5500
> ```

I think you need to use older python (3.10 should work). Easiest way to do so would be using pyenv.
With that being said, imo the docs should always support python installed in latest stable fedora - otherwise it adds unnecessary friction for developers.

**Comment by dgarcia360** [comment]
The docs are [compatible with Python 3.10](https://sphinx-theme.scylladb.com/stable/getting-started/installation.html). It's in our plans to make them compatible with [Python 3.12](https://github.com/scylladb/sphinx-scylladb-theme/issues/1007) , but this is not part of the current release.

cc/ @annastuchlik

**Review by Lorak-mmk — APPROVED** [review]

**Pull request merged**
