### PR TITLE
Fix RetryPolicy not retrying on Response::Error

### PR DESCRIPTION
**Pull request by cvybhu**
This is an alternative to #510.
`run_query` takes as a paramter a closure used to run a single query ona connection.
Result of such a query is `Result<ResT, QueryResult>`.

In Case of Result::Err the retry policy decides whether to retry the query based on the error type.

There was a bug - in a few cases `ResT` was of type `QueryResponse`, which has an `Error` variant. Such errors weren't detected by `RetryPolicy` and were never retried.

This PR fixes the bug by making the closure return `NonErrorQueryResponse`. All errors will be collected in a single `QueryResult` and detected by `RetryPolicy`.

Additionally to prevent such mistakes from happening a new trait is introduced that defines which types can be used as `ResT` in `run_query`:
```rust
pub trait AllowedRunQueryResTType {}

impl AllowedRunQueryResTType for Uuid {}
impl AllowedRunQueryResTType for BatchResult {}
impl AllowedRunQueryResTType for NonErrorQueryResponse {}
```

Fixes: #501

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [ ] I added relevant tests for new features and bug fixes.
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I added appropriate `Fixes:` annotations to PR description.

### CODE REVIEW

**Comment by wprzytula** [comment]
Unfortunately, this solution involves virtually duplicating the Response and QueryResponse struct as NonError- corresponding structs. That's far from elegant.

**Comment by cvybhu** [comment]
After discussing in person we are kinda leaning towards this one, @psarna whats your opinion?

**Comment by psarna** [comment]
I missed the notification before, but now that @piodul is going to be back on Monday anyway, let's roll him into the decision as well. Meanwhile, I'll also browse this suggestion

**Review by psarna — COMMENTED** [review]
Looks good - there's some duplication, but on the other hand the CQL protocol isn't very dynamic these days, so we can assume that we won't need to expand the response types enum any time soon, and even if, it would be just a single variant or two.

**Comment by wprzytula** [comment]
@piodul As testing my DowngradingConsistencyRetryPolicy PR depend on these changes, it would be great if you reviewed this soon.

**Review by psarna — APPROVED** [review]

**Review by piodul — APPROVED** [review]

**Pull request merged**
