### PR TITLE
Fixes to remove warnings on docs build

### PR DESCRIPTION
**Pull request by wprzytula**
## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [ ] All commit messages clearly explain what they change and why.
- [ ] ~~I added relevant tests for new features and bug fixes.~~
- [x] All commits compile, pass static checks and pass test.
- [ ] PR description sums up the changes and reasons why they should be introduced.
- [ ] ~~I added appropriate `Fixes:` annotations to PR description.~~

### CODE REVIEW

**Comment by piodul** [comment]
It looks like clippy update broke the CI again... I'll send a fix shortly.

**Comment by piodul** [comment]
@wprzytula I just realized that we don't have a CI check for `cargo doc`. Actually, even with your fix applied, I still get some warnings:

```
warning: unresolved link to `scylla::Session`
 --> scylla-cql/src/errors.rs:1:78
  |
1 | //! This module contains various errors which can be returned by [`Session`](scylla::Session)
  |                                                                              ^^^^^^^^^^^^^^^ no item named `scylla` in scope
  |
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default

warning: `scylla-cql` (lib doc) generated 1 warning
 Documenting scylla v0.5.0 (/home/piodul/code/scylla-rust-driver/scylla)
warning: unresolved link to `DefaultRetryPolicy`
  --> scylla/src/transport/downgrading_consistency_retry_policy.rs:11:62
   |
11 | /// that the initial CL is unreachable. Also, it behaves as [DefaultRetryPolicy] when it believes that the initial CL is reachable.
   |                                                              ^^^^^^^^^^^^^^^^^^ no item named `DefaultRetryPolicy` in scope
   |
   = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `exclusion_threshold`
  --> scylla/src/transport/load_balancing/latency_aware.rs:48:29
   |
48 |     /// average latency is [exclusion_threshold] times slower than the fastest node average
   |                             ^^^^^^^^^^^^^^^^^^^ no item named `exclusion_threshold` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `retry_period`
  --> scylla/src/transport/load_balancing/latency_aware.rs:50:43
   |
50 |     /// has been updated since less than [retry_period]. Since penalised nodes will likely not
   |                                           ^^^^^^^^^^^^ no item named `retry_period` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `minimum_measurements`
  --> scylla/src/transport/load_balancing/latency_aware.rs:67:59
   |
67 |     /// This is what this option controls. If fewer than [minimum_measurements] data
   |                                                           ^^^^^^^^^^^^^^^^^^^^ no item named `minimum_measurements` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `update_rate`
  --> scylla/src/transport/load_balancing/latency_aware.rs:74:91
   |
74 |     /// Last minimum average latency that was noted among the nodes. It is updated every [update_rate].
   |                                                                                           ^^^^^^^^^^^ no item named `update_rate` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: this URL is not a hyperlink
   --> scylla/src/statement/prepared_statement.rs:102:14
    |
102 |     /// Ref: https://github.com/scylladb/scylla/blob/40adf38915b6d8f5314c621a94d694d172360833/compound_compat.hh#L33-L47
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://github.com/scylladb/scylla/blob/40adf38915b6d8f5314c621a94d694d172360833/compound_compat.hh#L33-L47>`
    |
    = note: `#[warn(rustdoc::bare_urls)]` on by default
    = note: bare URLs are not automatically turned into clickable links

warning: this URL is not a hyperlink
  --> scylla/src/transport/downgrading_consistency_retry_policy.rs:13:5
   |
13 | ///(https://docs.datastax.com/en/drivers/java/3.11/com/datastax/driver/core/policies/DowngradingConsistencyRetryPolicy.html)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://docs.datastax.com/en/drivers/java/3.11/com/datastax/driver/core/policies/DowngradingConsistencyRetryPolicy.html>`
   |
   = note: bare URLs are not automatically turned into clickable links

warning: `scylla` (lib doc) generated 7 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 11.37s
```

Could you fix those issues too, please? It would also be good to add checking the docs for warnings as a step in CI - if you set an environment variable `RUSTDOCFLAGS=-Dwarnings`, you can turn those warnings into errors.

**Comment by wprzytula** [comment]
@piodul @cvybhu ready.

**Review by piodul — APPROVED** [review]
Thanks.

I just realized that I ran the `cargo doc` check on a non-main branch, so some of the warning I pasted were related to the latency-aware policy PR. Sorry for the confusion. Hopefully now you know what has to be fixed there :)

**Pull request merged**
